# Generated by Django 3.1.1 on 2020-09-14 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_num', models.CharField(auto_created=True, blank=True, max_length=256, null=True, verbose_name='Регистрационный номер')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Кличка')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo')),
                ('breed', models.CharField(max_length=256, verbose_name='Порода')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_registration', to='pets.registration', verbose_name='Регистрационный документ')),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal', verbose_name='Вид животного')),
            ],
        ),
    ]
