# Generated by Django 3.1.1 on 2020-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='character',
            field=models.TextField(default='', verbose_name='Характер'),
            preserve_default=False,
        ),
    ]
