# Generated by Django 3.1.1 on 2020-09-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_animal', to='pets.animal', verbose_name='Вид животного'),
        ),
    ]
