# Generated by Django 3.1.1 on 2020-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200915_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default='', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='character',
            field=models.TextField(blank=True, verbose_name='Характер'),
        ),
    ]
