# Generated by Django 3.1.1 on 2020-09-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20200917_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='slug',
        ),
    ]
